theme: jekyll-theme-time-machine
url: https://shanm.ca  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /shanminhas.github.io/      # place folder name if the site is served in a subfolder
